// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3d8wpdPp8UZ6959RyN3QZVN3bM4dMPDs',
    appId: '1:984533617408:web:d756e41300f74d7287c1e5',
    messagingSenderId: '984533617408',
    projectId: 'mapstate-7f210',
    authDomain: 'mapstate-7f210.firebaseapp.com',
    storageBucket: 'mapstate-7f210.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADFYWNt3h4FcmnK2YDpyh3bfAZPDOoM9w',
    appId: '1:984533617408:android:14dda0a28eaae7b887c1e5',
    messagingSenderId: '984533617408',
    projectId: 'mapstate-7f210',
    storageBucket: 'mapstate-7f210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAIHlRbqeaa4YVrmXAk7lkPzKMCI4dJvM',
    appId: '1:984533617408:ios:d1e5f9d7b9e1a3dc87c1e5',
    messagingSenderId: '984533617408',
    projectId: 'mapstate-7f210',
    storageBucket: 'mapstate-7f210.appspot.com',
    iosBundleId: 'com.example.haritaodev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAIHlRbqeaa4YVrmXAk7lkPzKMCI4dJvM',
    appId: '1:984533617408:ios:bbafed459ee5646e87c1e5',
    messagingSenderId: '984533617408',
    projectId: 'mapstate-7f210',
    storageBucket: 'mapstate-7f210.appspot.com',
    iosBundleId: 'com.example.haritaodev.RunnerTests',
  );
}
